from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from core.automation.models import Automation


@dataclass
class OutputContext:
    """
    Information available to an output plugin.

    `action_state` contains the shared state generated by the
    automation's action pipeline.
    """

    automation: Automation
    output_index: int

    action_state: dict[str, Any] = field(default_factory=dict)
    action_result: Any = None
    condition_result: Any = None

    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class OutputResult:
    """
    Standard result returned by every output plugin.
    """

    success: bool
    output_type: str

    data: Any = None
    message: str | None = None
    error: str | None = None

    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def succeeded(
        cls,
        *,
        output_type: str,
        data: Any = None,
        message: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> "OutputResult":
        return cls(
            success=True,
            output_type=output_type,
            data=data,
            message=message,
            metadata=metadata or {},
        )

    @classmethod
    def failed(
        cls,
        *,
        output_type: str,
        error: str,
        data: Any = None,
        metadata: dict[str, Any] | None = None,
    ) -> "OutputResult":
        return cls(
            success=False,
            output_type=output_type,
            data=data,
            error=error,
            metadata=metadata or {},
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "output_type": self.output_type,
            "data": self.data,
            "message": self.message,
            "error": self.error,
            "metadata": self.metadata,
        }


class BaseOutput(ABC):
    """
    Base class for every automation output plugin.
    """

    type: str = ""
    description: str = ""

    def validate_config(
        self,
        config: dict[str, Any],
    ) -> None:
        if not isinstance(config, dict):
            raise TypeError("Output config must be a dictionary.")

    @abstractmethod
    async def deliver(
        self,
        config: dict[str, Any],
        context: OutputContext,
    ) -> OutputResult:
        """
        Deliver an automation result.
        """
        raise NotImplementedError