import React,{useEffect,useState} from 'react';

const money=v=>v==null?'--':Number(v).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const pct=v=>v==null?'--':`${Number(v).toFixed(1)}%`;
const val=v=>v==null||v===''?'--':String(v);
const tone=s=>{s=String(s||'').toUpperCase();if(s==='SUCCESS')return 'reportGood';if(s==='FAILED')return 'reportBad';if(['PARTIAL_SUCCESS','IN_PROGRESS','WAITING_FOR_ENTRY','ORDER_UNFILLED'].includes(s))return 'reportWarn';if(s==='T1_THEN_STOP')return 'reportMixed';return 'reportNeutral';};
function Pill({children}){return <span className={`reportPill ${tone(children)}`}>{children}</span>}
function Card({label,value,sub}){return <div className="reportCard"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Empty({children='No report data yet.'}){return <div className="reportEmpty">{children}</div>}
function SetupTable({rows=[]}){return <div className="reportTableWrap"><table className="reportTable"><thead><tr><th>Symbol</th><th>Ready</th><th>Entry</th><th>Entry hit</th><th>T1</th><th>T1 hit</th><th>T2</th><th>T2 hit</th><th>Invalidation</th><th>Invalidation hit</th><th>Status</th><th>MFE</th><th>MAE</th><th>PAPER trade</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.symbol}-${r.ready_episode}-${i}`}><td><b>{r.symbol}</b><small className="reportSub">Ep {r.ready_episode} · {r.setup_type}</small></td><td>{val(r.ready_at)}</td><td>{money(r.entry)}</td><td>{val(r.entry_hit_at)}</td><td>{money(r.target1)}</td><td>{val(r.t1_hit_at)}</td><td>{money(r.target2)}</td><td>{val(r.t2_hit_at)}</td><td>{money(r.invalidation)}</td><td>{val(r.invalidation_hit_at)}</td><td><Pill>{r.status}</Pill></td><td>{pct(r.mfe_pct)}</td><td>{pct(r.mae_pct)}</td><td><Pill>{r.paper_status}</Pill></td></tr>)}</tbody></table></div>}
function PaperTable({rows=[]}){return <div className="reportTableWrap"><table className="reportTable"><thead><tr><th>Symbol</th><th>Episode</th><th>Order</th><th>Qty</th><th>Fill time</th><th>Fill</th><th>T1 hit</th><th>T2 hit</th><th>Invalidation hit</th><th>Status</th><th>MFE</th><th>MAE</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.paper_order_id}-${i}`}><td><b>{r.symbol}</b></td><td>{r.ready_episode}</td><td>{val(r.paper_order_id)}</td><td>{val(r.paper_quantity)}</td><td>{val(r.paper_fill_at)}</td><td>{money(r.paper_fill_price)}</td><td>{val(r.paper_t1_hit_at)}</td><td>{val(r.paper_t2_hit_at)}</td><td>{val(r.paper_invalidation_hit_at)}</td><td><Pill>{r.paper_status}</Pill></td><td>{pct(r.paper_mfe_pct)}</td><td>{pct(r.paper_mae_pct)}</td></tr>)}</tbody></table></div>}

export default function Reports(){
 const[days,setDays]=useState(30),[data,setData]=useState(null),[err,setErr]=useState(''),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setErr('');try{const r=await fetch(`/api/v1512/reports?days=${days}`);if(!r.ok)throw new Error(await r.text());setData(await r.json())}catch(e){setErr(String(e))}finally{setLoading(false)}};
 useEffect(()=>{load()},[days]);
 const s=data?.summary||{};
 const tabs=[['overview','Overview'],['daily','Daily'],['baby','Baby Performance'],['paper','My PAPER Trades'],['open','Open Setups'],['blockers','Blockers'],['types','Setup Types'],['health','Alert Health']];
 return <main className="screenPage reportsPage">
  <section className="pageExplain compactExplain"><div><span className="pageKicker">REPORTS</span><h1>Baby performance and daily activity</h1><p>Measure Baby's SETUP_READY suggestions independently from the Alpaca PAPER trades you actually approve. Milestone dates are shown in Eastern Time.</p></div><div className="reportActions"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>Today</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={3650}>All</option></select><button className="primaryButton" onClick={()=>window.location.href=`/api/v1512/reports/pdf?days=${days}`}>Download PDF</button><button className="secondaryButton" onClick={load}>Refresh</button></div></section>
  <div className="plainHelpBox"><b>Three separate views of Baby history</b><span><strong>Historical Observations</strong> includes persisted monitoring history, including conservative pre-V15.12 backfill records.</span><span><strong>Baby Performance</strong> tracks only true SETUP_READY plans whether you traded them or not.</span><span><strong>My PAPER Trades</strong> begins only after an actual Alpaca PAPER fill.</span><span>Historical MONITOR observations are never treated as trades, wins, losses, or SETUP_READY episodes.</span></div>
  {err&&<div className="notice">{err}</div>}{loading&&!data&&<div className="reportEmpty">Loading reports…</div>}
  {data&&<><div className="reportCards"><Card label="HISTORICAL OBSERVATIONS" value={s.historical_observations??0} sub={`${s.symbols_monitored??0} symbols monitored`}/><Card label="BACKFILLED HISTORY" value={s.historical_backfill_observations??0} sub={s.history_first_seen?`since ${s.history_first_seen}`:'no historical range'}/><Card label="SETUP READY" value={s.setup_ready_episodes??0} sub={`${s.unique_symbols??0} unique SETUP_READY symbols`}/><Card label="ENTRY RATE" value={pct(s.entry_rate_pct)} sub={`${s.entries_established??0} entries established`}/><Card label="T1 HIT RATE" value={pct(s.t1_rate_pct)} sub="after entry"/><Card label="T2 HIT RATE" value={pct(s.t2_rate_pct)} sub="after entry"/><Card label="FAILED BEFORE T1" value={pct(s.stop_before_t1_rate_pct)} sub={`${s.failed_before_t1??0} setups`}/><Card label="ACTUAL PAPER TRADES" value={s.actual_paper_trades??0} sub="user approved"/></div>
  <div className="reportTabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='overview'&&<div className="reportGrid"><section className="reportPanel"><h2>Historical coverage</h2><div className="reportStatusGrid"><div><span>Observations</span><b>{s.historical_observations??0}</b></div><div><span>Symbols monitored</span><b>{s.symbols_monitored??0}</b></div><div><span>First observation</span><b>{val(s.history_first_seen)}</b></div><div><span>Latest observation</span><b>{val(s.history_last_seen)}</b></div></div><p className="reportNote">{s.historical_backfill_observations??0} observations were conservatively reconstructed from persisted pre-V15.12 monitoring history. They remain monitoring records only and are not counted as SETUP_READY performance.</p></section><section className="reportPanel"><h2>Current performance</h2><div className="reportStatusGrid"><div><span>Waiting for entry</span><b>{s.waiting_for_entry??0}</b></div><div><span>Open / unresolved</span><b>{s.open_setups??0}</b></div><div><span>T1 hits</span><b>{s.t1_hits??0}</b></div><div><span>T2 hits</span><b>{s.t2_hits??0}</b></div></div></section><section className="reportPanel"><h2>Latest daily activity</h2>{!data.daily?.length?<Empty/>:<>{data.daily.slice(0,5).map(r=><div className="dailyMini" key={r.date}><b>{r.date}</b><span>{r.symbols_observed} observed · {r.monitor} monitor · {r.setup_forming} forming · {r.active_setup} active · {r.near_ready} near-ready · {r.setup_ready_episodes} ready episodes</span></div>)}</>}</section><section className="reportPanel reportWide"><h2>Latest Baby SETUP_READY episodes</h2>{!data.baby_performance?.length?<Empty>No SETUP_READY episodes in this window.</Empty>:<SetupTable rows={data.baby_performance.slice(0,12)}/>}</section></div>}
  {tab==='daily'&&<section className="reportPanel"><h2>Daily activity report</h2>{!data.daily?.length?<Empty/>:<div className="reportTableWrap"><table className="reportTable"><thead><tr><th>Date</th><th>Observed</th><th>Monitor</th><th>Setup forming</th><th>Active</th><th>Near ready</th><th>SETUP_READY episodes</th><th>Approvals</th><th>PAPER orders</th><th>Fills</th><th>Emails sent</th><th>Email failures</th></tr></thead><tbody>{data.daily.map(r=><tr key={r.date}><td><b>{r.date}</b></td><td>{r.symbols_observed}</td><td>{r.monitor}</td><td>{r.setup_forming}</td><td>{r.active_setup}</td><td>{r.near_ready}</td><td>{r.setup_ready_episodes}</td><td>{r.approvals_created}</td><td>{r.paper_orders_submitted}</td><td>{r.paper_fills}</td><td>{r.emails_sent}</td><td>{r.email_failures}</td></tr>)}</tbody></table></div>}</section>}
  {tab==='baby'&&<section className="reportPanel"><h2>Baby recommendation performance</h2><p className="reportNote">This evaluates Baby itself. A setup is tracked even if you never approved a PAPER trade.</p>{!data.baby_performance?.length?<Empty/>:<SetupTable rows={data.baby_performance}/>}</section>}
  {tab==='paper'&&<section className="reportPanel"><h2>My Alpaca PAPER trades</h2><p className="reportNote">This report starts at the actual broker fill, not the theoretical entry.</p>{!data.paper_trades?.length?<Empty>No approved Alpaca PAPER trades in this window.</Empty>:<PaperTable rows={data.paper_trades}/>}</section>}
  {tab==='open'&&<section className="reportPanel"><h2>Open / unresolved Baby setups</h2>{!data.open_setups?.length?<Empty>No unresolved SETUP_READY episodes.</Empty>:<SetupTable rows={data.open_setups}/>}</section>}
  {tab==='blockers'&&<section className="reportPanel"><h2>Why candidates did not become PAPER ready</h2>{!data.blockers?.length?<Empty/>:<div className="reportTableWrap"><table className="reportTable"><thead><tr><th>Blocker</th><th>Unique symbol-day count</th><th>Examples</th></tr></thead><tbody>{data.blockers.map(r=><tr key={r.blocker}><td><b>{r.blocker}</b></td><td>{r.count}</td><td>{r.symbols?.join(', ')||'--'}</td></tr>)}</tbody></table></div>}</section>}
  {tab==='types'&&<section className="reportPanel"><h2>Performance by setup type</h2>{!data.setup_types?.length?<Empty/>:<div className="reportTableWrap"><table className="reportTable"><thead><tr><th>Setup type</th><th>Ready</th><th>Entered</th><th>Entry rate</th><th>T1 hits</th><th>T1 rate</th><th>T2 hits</th><th>T2 rate</th><th>Failed before T1</th><th>Stop rate</th><th>Open</th></tr></thead><tbody>{data.setup_types.map(r=><tr key={r.setup_type}><td><b>{r.setup_type}</b></td><td>{r.ready_episodes}</td><td>{r.entered}</td><td>{pct(r.entry_rate_pct)}</td><td>{r.t1_hits}</td><td>{pct(r.t1_rate_pct)}</td><td>{r.t2_hits}</td><td>{pct(r.t2_rate_pct)}</td><td>{r.failed_before_t1}</td><td>{pct(r.stop_before_t1_rate_pct)}</td><td>{r.open}</td></tr>)}</tbody></table></div>}</section>}
  {tab==='health'&&<section className="reportPanel"><h2>Alert and approval health</h2><div className="reportJson"><div><h3>Email delivery</h3><pre>{JSON.stringify(data.alert_health?.email_status||{},null,2)}</pre></div><div><h3>Email events</h3><pre>{JSON.stringify(data.alert_health?.email_events||{},null,2)}</pre></div><div><h3>Approval states</h3><pre>{JSON.stringify(data.alert_health?.approval_status||{},null,2)}</pre></div></div></section>}</>}
 </main>
}
