import React,{useEffect,useMemo,useRef,useState} from 'react';import {api} from '../lib/api';import LiveQuote from '../components/LiveQuote';import Pipeline from '../components/Pipeline';import MetricCard from '../components/MetricCard';import {ShieldAlert,RefreshCw,Play,CheckCircle2,AlertTriangle} from 'lucide-react';
export default function Research({initialSymbol="AAPL"}){
 const [symbol,setSymbol]=useState(initialSymbol),[draft,setDraft]=useState(initialSymbol),[report,setReport]=useState(null),[glossary,setGlossary]=useState({}),[active,setActive]=useState('data'),[error,setError]=useState(''),[job,setJob]=useState(null),[busy,setBusy]=useState(false);const poll=useRef(null);
 const load=async s=>{setError('');try{const r=await api.research(s);if(r.research_status==='NOT_RESEARCHED'){setReport(null);setJob(r.job);return false}setReport(r);setJob({status:'READY'});setActive(r.stages?.[0]?.id||'data');return true}catch(e){setError(String(e));return false}};
 const watch=async s=>{clearInterval(poll.current);poll.current=setInterval(async()=>{const st=await api.researchStatus(s);setJob(st);if(st.status==='READY'){clearInterval(poll.current);setBusy(false);await load(s)}else if(st.status==='ERROR'){clearInterval(poll.current);setBusy(false);setError(st.error||'Research failed')}},1200)};
 const run=async(force=false)=>{setBusy(true);setError('');try{const st=await api.runResearch(symbol,force);setJob(st);if(st.status==='READY'){setBusy(false);await load(symbol)}else watch(symbol)}catch(e){setBusy(false);setError(String(e))}};
 useEffect(()=>{api.glossary().then(setGlossary);load(symbol);return()=>clearInterval(poll.current)},[]);
 const open=async s=>{s=s.toUpperCase();setSymbol(s);setReport(null);setJob(null);await load(s)};
 const stage=useMemo(()=>report?.stages?.find(s=>s.id===active),[report,active]);
 return <main><header className="topbar"><div><div className="brand">BABY <span>INVESTMENT INTELLIGENCE</span></div><p>Production research · auditable evidence · AI scoring authority 0%</p></div><form onSubmit={e=>{e.preventDefault();open(draft)}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ticker"/><button>Open research</button></form></header>
 {error&&<div className="notice"><AlertTriangle size={18}/>{error}</div>}
 <section className="hero"><div><h1>{symbol} <span>{report?.company_name}</span></h1><LiveQuote symbol={symbol}/></div>
 <div className="scoreGrid"><K label="BABY STATUS" v={report?.decision||'NOT RESEARCHED'}/><K label="RESEARCH SCORE" v={report?.score!=null?`${Number(report.score).toFixed(1)}/100`:'UNKNOWN'}/><K label="CONFIDENCE" v={report?.confidence!=null?`${report.confidence}%`:'UNKNOWN'}/><K label="EVIDENCE COVERAGE" v={report?.coverage!=null?`${report.coverage}%`:'UNKNOWN'}/><K label="UNIFIED RISK" v={report?.risk||'UNKNOWN'} danger={report?.hard_risk_override}/><K label="VALIDATION" v={report?.validation_status||'UNKNOWN'}/></div>
 <div className="snapshot">Research snapshot: {report?.generated_at?new Date(report.generated_at).toLocaleString():'not generated'} · Quote timestamp is independent.</div>
 <div className="researchActions">{!report&&<button className="primaryAction" disabled={busy||job?.status==='RUNNING'} onClick={()=>run(false)}><Play size={17}/> Run full Baby research</button>}{report&&<button className="primaryAction" disabled={busy} onClick={()=>run(true)}><RefreshCw size={17} className={busy?'spin':''}/> Refresh full research</button>}<Job job={job}/></div></section>
 {!report&&<section className="emptyResearch"><h2>{job?.status==='RUNNING'||job?.status==='QUEUED'?'Baby is researching '+symbol:`${symbol} has not been researched yet`}</h2><p>{job?.stage||'Run the production Baby Investor pipeline. The UI will populate automatically when it finishes.'}</p>{(job?.status==='RUNNING'||job?.status==='QUEUED')&&<div className="progress"><div/></div>}</section>}
 {report&&<div className="layout"><aside><h3>RESEARCH PIPELINE</h3><Pipeline stages={report.stages||[]} active={active} onSelect={setActive}/></aside><section className="stage"><div className="stageHead"><div><span className="eyebrow">STAGE {String((report.stages||[]).findIndex(x=>x.id===active)+1).padStart(2,'0')}</span><h2>{stage?.label}</h2><p>{stage?.summary}</p></div><div className={`badge status-${stage?.status?.toLowerCase()}`}>{stage?.status}</div></div><div className="metrics">{(stage?.metrics||[]).map(m=><MetricCard key={m.key} m={m} glossary={glossary}/>)}</div><Reasoning stage={stage}/>{active==='trade'&&<JsonPanel title="TRADE PLAN" data={report.trade_plan}/>} {active==='portfolio'&&<JsonPanel title="PORTFOLIO IMPACT" data={report.portfolio_impact}/>} {active==='history'&&<JsonPanel title="HISTORICAL VALIDATION" data={report.historical_validation}/>}<div className="authority"><ShieldAlert size={18}/><div><b>Authority boundary</b><span>AI scoring authority: {report.ai_scoring_authority??0}% · AI execution authority: {report.ai_execution_authority||'NONE'} · Real-money execution is disabled.</span></div></div></section></div>}</main>}
function Job({job}){if(!job)return null;const running=['QUEUED','RUNNING'].includes(job.status);return <div className={`jobState ${job.status?.toLowerCase()}`}>{running?<RefreshCw size={16} className="spin"/>:<CheckCircle2 size={16}/>}<span>{job.status}{job.stage?` · ${job.stage}`:''}</span></div>}
function K({label,v,danger}) {return <div className={`kpi ${danger?'danger':''}`}><small>{label}</small><strong>{v}</strong></div>}
function Reasoning({stage}){const groups=[['Positive evidence',stage?.positives,'good'],['Negative evidence',stage?.negatives,'bad'],['Unknown evidence',stage?.unknowns,'unknown'],['Conflicting evidence',stage?.conflicts,'conflict']];return <div className="reason"><h3>AUDITABLE REASONING OUTPUT</h3><p className="muted">Inspectable evidence, formulas and rule outputs — not hidden LLM chain-of-thought.</p>{groups.map(([n,a,c])=>(a?.length?<div key={n}><b>{n}</b>{a.map((x,i)=><p className={c} key={i}>• {x}</p>)}</div>:null))}{!groups.some(x=>x[1]?.length)&&<p className="muted">No structured reasons exported for this stage. Missing evidence remains UNKNOWN.</p>}</div>}
function JsonPanel({title,data}){return <div className="jsonPanel"><h3>{title}</h3><pre>{JSON.stringify(data||{},null,2)}</pre></div>}
