export const api={
 stockHistory:(s,r='1M')=>fetch(`/api/history/stock/${s}?range_name=${r}`).then(x=>x.json()),
 portfolioHistory:()=>fetch('/api/history/portfolio').then(x=>x.json()),
 monitorSync:()=>fetch('/api/monitor/sync',{method:'POST'}).then(x=>x.json()),
 schedulerStatus:()=>fetch('/api/scheduler/status').then(x=>x.json()),

 productionHealth:()=>fetch('/api/production/health').then(r=>r.json()),
 productionDecision:(s,p={})=>fetch(`/api/production/decision/${s}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json()),
 monitorJobs:()=>fetch('/api/monitor/jobs').then(r=>r.json()),
 monitorEvents:(s='')=>fetch('/api/monitor/events'+(s?`?symbol=${encodeURIComponent(s)}`:'')).then(r=>r.json()),
 monitorRegister:(s,p={})=>fetch(`/api/monitor/jobs/${s}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json()),
 monitorRun:s=>fetch(`/api/monitor/jobs/${s}/run`,{method:'POST'}).then(r=>r.json()),
 monitorDisable:s=>fetch(`/api/monitor/jobs/${s}`,{method:'DELETE'}).then(r=>r.json()),

 health:()=>fetch('/api/health').then(r=>r.json()),
 glossary:()=>fetch('/api/glossary').then(r=>r.json()),
 legend:()=>fetch('/api/research/legend/all').then(r=>r.json()),
 explainStage:(s,id)=>fetch(`/api/research/${s}/explain/${id}`).then(r=>r.json()),
 copilot:(message,context={},session_id='')=>fetch('/api/copilot/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,context,session_id})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 research:async s=>{const r=await fetch(`/api/research/${s}`); if(!r.ok) throw new Error(await r.text()); return r.json()},
 researchStatus:s=>fetch(`/api/research/${s}/status`).then(r=>r.json()),
 runResearch:(s,force=false)=>fetch(`/api/research/${s}/run?force=${force}`,{method:'POST'}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alerts:()=>fetch('/api/alerts').then(r=>r.json()),
 control:()=>fetch('/api/control/status').then(r=>r.json()),
 backtest:()=>fetch('/api/backtests/v7_5').then(r=>r.json()),
 paper:()=>fetch('/api/portfolio/paper').then(r=>r.json()),
 paperOrder:p=>fetch('/api/portfolio/paper/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 executePaperOrder:id=>fetch(`/api/portfolio/paper/orders/${id}/execute`,{method:'POST'}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 paperProposal:s=>fetch(`/api/research/${s}/paper-proposal`).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 createProposalOrder:s=>fetch(`/api/research/${s}/paper-proposal/order`,{method:'POST'}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alpacaStatus:()=>fetch('/api/broker/alpaca/status').then(r=>r.json()),
 alpacaPositions:()=>fetch('/api/broker/alpaca/positions').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alpacaOrders:()=>fetch('/api/broker/alpaca/orders').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alpacaOrder:p=>fetch('/api/broker/alpaca/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alpacaCancel:id=>fetch(`/api/broker/alpaca/orders/${id}`,{method:'DELETE'}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alpacaResearchProposal:s=>fetch(`/api/research/${s}/alpaca-paper-proposal`).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 alpacaResearchOrder:(s,confirmation)=>fetch(`/api/research/${s}/alpaca-paper-order`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 monitoredSetups:()=>fetch('/api/portfolio/monitored-setups').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 removeMonitoredSetup:s=>fetch(`/api/portfolio/monitored-setups/${s}`,{method:'DELETE'}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 emailStatus:()=>fetch('/api/email/status').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 emailSubscribers:()=>fetch('/api/email/subscribers').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 addEmailSubscriber:email=>fetch('/api/email/subscribers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 verifyEmailSubscriber:(email,code)=>fetch('/api/email/subscribers/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 resendEmailSubscriber:email=>fetch('/api/email/subscribers/resend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 removeEmailSubscriber:id=>fetch(`/api/email/subscribers/${id}`,{method:'DELETE'}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),
 emailDeliveries:()=>fetch('/api/email/deliveries?limit=50').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}),

 automations:()=>fetch('/api/automations').then(r=>r.json()),
 scanner:()=>fetch('/api/scanner/latest').then(r=>r.json()),
};
export function marketSocket(symbol,onQuote){const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${proto}://${location.host}/ws/market/${symbol}`);ws.onmessage=e=>onQuote(JSON.parse(e.data));return ws}
